#PS1="%F{39}%n@%F{210}%m %1 %F{82}~ %F{63}%# %F"    #basic 
#PS1="%F{39}%n@%F{210}%m %1 %F{63}%# %F"	    #basic2
PS1="%F{210}%1d %F{cyan}% -> %F"		    #current folder
#PS1="%F{cyan}% -> %F"				    #arrow
#PS1="%F{210}%m %F{cyan}% -> %F"		    #dev name
export PATH="/opt/homebrew/bin:$PATH"
export PATH="/opt/homebrew/sbin:$PATH"
export PATH="/usr/local/git/bin:$PATH"
#export CLICOLOR=1
#alias mpv="~/Applications/mpv/build/mpv --fs"
alias alivesince="system_profiler SPSoftwareDataType -detailLevel mini | grep Time"
alias hackerman="cmatrix -sa"
alias venv="source ~/dev/myvenv/bin/activate"
#alias fixmpv="brew install --build-from-source --only-dependencies mpv && brew install libplacebo"
alias folders="ls -d */"
alias full-size="du -sch"
alias apt="brew"
alias cowtune="fortune | cowsay | lolcat"
alias cls="clear"
alias vidformat="handbrakecli -q 22.0 -b 1000"
#alias updateuptime="alivesince > ~/.uptime.txt"
#alias bestuptime="cat ~/.uptime.txt"
alias ls="ls -G"
alias lsa="ls -Ga"
alias lsl="ls -Gal"
alias resetdock="defaults delete com.apple.dock; killall Dock"
alias die="exit"
alias batterycycles="system_profiler SPPowerDataType | grep "Cycle" && system_profiler SPPowerDataType | grep "Condition" && system_profiler SPPowerDataType | grep "Capacity""
alias sort-downloads="python3 ~/Documents/Scripts/sort-downloads.py"
#alias up="/Users/migaragunawansha/Documents/Scripts/uptime_updater.zsh"
alias tn='tmux new'
alias ta='tmux attach'
alias tk='tmux kill-session'
alias youtube='yt-dlp -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best"'
alias sleepstatus='pmset -g | awk "/SleepDisabled/{print $2}"'
alias sleeprecord='pmset -g log | grep -e "Clamshell Sleep" -e " Wake  " | tail -n '
alias stayup='caffeinate -d -t '
alias fsizes='du -sh ./* | sort -h'
alias la='ls -la'
alias folder-copy='sudo ~/Documents/Scripts/folder-copy.sh'
alias spank='sudo ~/Documents/Scripts/spank_1.2.5_darwin_arm64/spank'
